#Requires -Modules DnsServer

<#
.SYNOPSIS
    Interactively deletes DNS records based on a JSON audit file.

.DESCRIPTION
    This script reads a JSON file produced by Invoke-DNSAgeAudit.ps1 and allows
    administrators to selectively delete DNS records through an interactive menu system.
    Supports filtering by age category, zone, and record type.

.PARAMETER JSONPath
    Path to the JSON audit file generated by Invoke-DNSAgeAudit.ps1

.PARAMETER DNSServer
    The DNS server to delete records from (defaults to server in JSON file)

.PARAMETER WhatIf
    Shows what would be deleted without actually deleting

.PARAMETER AgeFilter
    Filter to specific age category: Over365Days, Over180Days, Over90Days, Static

.PARAMETER ZoneFilter
    Filter to specific DNS zone name

.PARAMETER RecordTypeFilter
    Filter to specific record type (A, AAAA, CNAME, etc.)

.PARAMETER AutoApprove
    Automatically approve all deletions without prompting (use with caution!)

.PARAMETER CheckOnline
    Check if devices are online before deleting (uses TCP port checks, not ICMP ping)

.PARAMETER SkipOnline
    Automatically skip devices that are online (requires -CheckOnline)

.EXAMPLE
    .\Invoke-DNSCleanup.ps1 -JSONPath "C:\Reports\DNS\DNSAgeAudit-20250101-120000.json"

.EXAMPLE
    .\Invoke-DNSCleanup.ps1 -JSONPath "C:\Reports\DNS\DNSAgeAudit-20250101-120000.json" -CheckOnline -SkipOnline

.EXAMPLE
    .\Invoke-DNSCleanup.ps1 -JSONPath "C:\Reports\DNS\DNSAgeAudit-20250101-120000.json" -AgeFilter "Over365Days" -WhatIf

.EXAMPLE
    .\Invoke-DNSCleanup.ps1 -JSONPath "C:\Reports\DNS\DNSAgeAudit-20250101-120000.json" -ZoneFilter "contoso.com" -RecordTypeFilter "A"

.NOTES
    Author: SysAdmin Tools
    Requires: DNS Server PowerShell module and Administrator privileges
    CAUTION: This script deletes DNS records. Always test with -WhatIf first!
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$JSONPath,

    [string]$DNSServer,

    [switch]$WhatIf,

    [ValidateSet("Over365Days", "Over180Days", "Over90Days", "Static", "All")]
    [string]$AgeFilter = "All",

    [string]$ZoneFilter,

    [string]$RecordTypeFilter,

    [switch]$AutoApprove,

    [switch]$CheckOnline,

    [switch]$SkipOnline,

    [string]$LogPath = "C:\Reports\DNS\DNSCleanup-Log.csv"
)

$ErrorActionPreference = "Stop"

function Import-DNSAuditData {
    param([string]$Path)

    Write-Output "Loading DNS audit data from: $Path"

    if (-not (Test-Path $Path)) {
        Write-Error "JSON file not found: $Path"
        throw
    }

    try {
        $data = Get-Content -Path $Path -Raw | ConvertFrom-Json
        Write-Output "Loaded $($data.TotalRecords) records from audit file"
        Write-Output "Audit generated: $($data.GeneratedDate)"
        Write-Output "DNS Server: $($data.DNSServer)"
        return $data
    } catch {
        Write-Error "Failed to parse JSON file: $_"
        throw
    }
}

function Test-DeviceOnline {
    param(
        [string]$IPAddress,
        [int]$TimeoutMs = 1000
    )

    if (-not $IPAddress) { return $false }

    $portsToTest = @(5985, 443, 80, 3389, 22)

    foreach ($port in $portsToTest) {
        try {
            $tcpClient = New-Object System.Net.Sockets.TcpClient
            $connectTask = $tcpClient.ConnectAsync($IPAddress, $port)
            $waitTask = $connectTask.Wait($TimeoutMs)
            
            if ($waitTask -and $tcpClient.Connected) {
                $tcpClient.Close()
                return $true
            }
            $tcpClient.Close()
        } catch {
            continue
        }
    }

    return $false
}

function Get-FilteredRecords {
    param(
        [array]$Records,
        [string]$AgeFilter,
        [string]$ZoneFilter,
        [string]$RecordTypeFilter
    )

    $filtered = $Records

    if ($AgeFilter -ne "All") {
        $filtered = $filtered | Where-Object { $_.AgeCategory -eq $AgeFilter }
        Write-Output "Applied age filter: $AgeFilter"
    }

    if ($ZoneFilter) {
        $filtered = $filtered | Where-Object { $_.ZoneName -like $ZoneFilter }
        Write-Output "Applied zone filter: $ZoneFilter"
    }

    if ($RecordTypeFilter) {
        $filtered = $filtered | Where-Object { $_.RecordType -eq $RecordTypeFilter }
        Write-Output "Applied record type filter: $RecordTypeFilter"
    }

    Write-Output "Filtered to $($filtered.Count) records"
    return $filtered
}

function Show-RecordSelectionMenu {
    param([array]$Records)

    Write-Output ""
    Write-Output "=" * 80
    Write-Output "DNS Record Selection Menu"
    Write-Output "=" * 80
    Write-Output ""
    Write-Output "Available records: $($Records.Count)"
    Write-Output ""

    $grouped = $Records | Group-Object -Property AgeCategory
    foreach ($group in ($grouped | Sort-Object Name)) {
        Write-Output "  [$($group.Name)]: $($group.Count) records"
    }

    Write-Output ""
    Write-Output "Options:"
    Write-Output "  1. View all filtered records"
    Write-Output "  2. Select records by age category"
    Write-Output "  3. Select records by zone"
    Write-Output "  4. Select records by record type"
    Write-Output "  5. Select specific records manually"
    Write-Output "  6. Delete all filtered records"
    Write-Output "  7. Export filtered records to CSV"
    Write-Output "  8. Exit"
    Write-Output ""

    $choice = Read-Host "Enter your choice (1-8)"
    return $choice
}

function Show-RecordList {
    param(
        [array]$Records,
        [int]$PageSize = 20
    )

    $totalPages = [Math]::Ceiling($Records.Count / $PageSize)
    $currentPage = 1

    while ($true) {
        $startIndex = ($currentPage - 1) * $PageSize
        $endIndex = [Math]::Min($startIndex + $PageSize, $Records.Count) - 1

        Write-Output ""
        Write-Output "=" * 80
        Write-Output "Records (Page $currentPage of $totalPages)"
        Write-Output "=" * 80
        Write-Output ""

        for ($i = $startIndex; $i -le $endIndex; $i++) {
            $record = $Records[$i]
            $index = $i + 1
            $ageDisplay = if ($record.Age) { "$($record.Age) days" } else { "Static" }

            $statusDisplay = ""
            if ($script:CheckOnline -and ($record.RecordType -eq "A" -or $record.RecordType -eq "AAAA")) {
                if ($record.OnlineStatus) {
                    $statusDisplay = " [ONLINE]"
                } elseif ($record.OnlineStatus -eq $false) {
                    $statusDisplay = " [OFFLINE]"
                }
            }

            Write-Output "[$index] $($record.ZoneName) | $($record.HostName) | $($record.RecordType) | $($record.RecordData) | Age: $ageDisplay$statusDisplay"
        }

        Write-Output ""
        Write-Output "Navigation: [N]ext page, [P]revious page, [Q]uit to menu"
        $nav = Read-Host "Enter choice"

        switch ($nav.ToUpper()) {
            "N" {
                if ($currentPage -lt $totalPages) {
                    $currentPage++
                } else {
                    Write-Output "Already on last page"
                }
            }
            "P" {
                if ($currentPage -gt 1) {
                    $currentPage--
                } else {
                    Write-Output "Already on first page"
                }
            }
            "Q" { return }
        }
    }
}

function Select-RecordsByIndex {
    param([array]$Records)

    Write-Output ""
    Write-Output "Enter record indices to delete (comma-separated, or ranges like 1-5)"
    Write-Output "Example: 1,3,5-10,15"
    Write-Output ""

    $input = Read-Host "Indices"

    $selectedIndices = @()
    $parts = $input -split ','

    foreach ($part in $parts) {
        $part = $part.Trim()

        if ($part -match '^(\d+)-(\d+)$') {
            $start = [int]$matches[1]
            $end = [int]$matches[2]
            $selectedIndices += ($start..$end)
        } elseif ($part -match '^\d+$') {
            $selectedIndices += [int]$part
        }
    }

    $selected = @()
    foreach ($index in $selectedIndices) {
        if ($index -ge 1 -and $index -le $Records.Count) {
            $selected += $Records[$index - 1]
        }
    }

    Write-Output "Selected $($selected.Count) records"
    return $selected
}

function Remove-DNSRecords {
    param(
        [array]$Records,
        [string]$Server,
        [bool]$WhatIfMode,
        [bool]$AutoApprove
    )

    if ($Records.Count -eq 0) {
        Write-Output "No records to delete"
        return @()
    }

    Write-Output ""
    Write-Output "=" * 80
    Write-Output "Deletion Summary"
    Write-Output "=" * 80
    Write-Output ""
    Write-Output "DNS Server: $Server"
    Write-Output "Records to delete: $($Records.Count)"
    Write-Output ""

    if ($script:CheckOnline) {
        $onlineToDel = ($Records | Where-Object { $_.OnlineStatus -eq $true }).Count
        $offlineToDel = ($Records | Where-Object { $_.OnlineStatus -eq $false }).Count
        Write-Output "Online status:"
        Write-Output "  Online: $onlineToDel"
        Write-Output "  Offline: $offlineToDel"
        Write-Output ""
    }

    $grouped = $Records | Group-Object -Property AgeCategory
    foreach ($group in ($grouped | Sort-Object Name)) {
        Write-Output "  $($group.Name): $($group.Count) records"
    }

    Write-Output ""

    if ($WhatIfMode) {
        Write-Output "[WHATIF MODE] No records will actually be deleted"
        Write-Output ""
    }

    if (-not $AutoApprove) {
        $confirm = Read-Host "Are you sure you want to delete these records? (YES to confirm)"
        if ($confirm -ne "YES") {
            Write-Output "Deletion cancelled"
            return @()
        }
    }

    Write-Output ""
    Write-Output "Processing deletions..."

    $deletionLog = @()
    $successCount = 0
    $failCount = 0
    $skippedCount = 0

    foreach ($record in $Records) {
        if ($script:SkipOnline -and $record.OnlineStatus -eq $true) {
            Write-Output "[SKIPPED - ONLINE] $($record.ZoneName)\$($record.HostName) ($($record.RecordType))"
            $logEntry = [PSCustomObject]@{
                Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
                ZoneName = $record.ZoneName
                HostName = $record.HostName
                RecordType = $record.RecordType
                RecordData = $record.RecordData
                Age = $record.Age
                OnlineStatus = $record.OnlineStatus
                Status = "Skipped-Online"
                Error = ""
            }
            $deletionLog += $logEntry
            $skippedCount++
            continue
        }
        $onlineStatus = if ($script:CheckOnline -and ($record.RecordType -eq "A" -or $record.RecordType -eq "AAAA")) {
            $record.OnlineStatus
        } else {
            $null
        }
        $logEntry = [PSCustomObject]@{
            Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
            ZoneName = $record.ZoneName
            HostName = $record.HostName
            RecordType = $record.RecordType
            RecordData = $record.RecordData
            Age = $record.Age
            OnlineStatus = $onlineStatus
            Status = ""
            Error = ""
        }

        try {
            if ($WhatIfMode) {
                Write-Output "[WHATIF] Would delete: $($record.ZoneName)\$($record.HostName) ($($record.RecordType))"
                $logEntry.Status = "WhatIf"
                $successCount++
            } else {
                Remove-DnsServerResourceRecord -ComputerName $Server -ZoneName $record.ZoneName -Name $record.HostName -RRType $record.RecordType -Force -ErrorAction Stop
                Write-Output "[DELETED] $($record.ZoneName)\$($record.HostName) ($($record.RecordType))"
                $logEntry.Status = "Deleted"
                $successCount++
            }
        } catch {
            Write-Warning "[FAILED] $($record.ZoneName)\$($record.HostName) ($($record.RecordType)): $_"
            $logEntry.Status = "Failed"
            $logEntry.Error = $_.Exception.Message
            $failCount++
        }

        $deletionLog += $logEntry
    }

    Write-Output ""
    Write-Output "Deletion complete:"
    Write-Output "  Success: $successCount"
    Write-Output "  Failed:  $failCount"
    if ($skippedCount -gt 0) {
        Write-Output "  Skipped (Online): $skippedCount"
    }

    return $deletionLog
}

function Export-DeletionLog {
    param(
        [array]$Log,
        [string]$Path
    )

    if ($Log.Count -eq 0) {
        return
    }

    $outputDir = Split-Path -Parent $Path
    if (!(Test-Path $outputDir)) {
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
    }

    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $logFile = $Path -replace "\.csv$", "-$timestamp.csv"

    $Log | Export-Csv -Path $logFile -NoTypeInformation -Append
    Write-Output "Deletion log saved to: $logFile"
}

function Export-FilteredRecordsToCSV {
    param(
        [array]$Records,
        [string]$OutputPath
    )

    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $csvPath = Join-Path (Split-Path $OutputPath) "DNSRecords-Filtered-$timestamp.csv"

    $Records | Export-Csv -Path $csvPath -NoTypeInformation
    Write-Output "Filtered records exported to: $csvPath"
}

try {
    Write-Output "DNS Cleanup Utility"
    Write-Output "=" * 80
    Write-Output ""

    $auditData = Import-DNSAuditData -Path $JSONPath

    $dnsServer = if ($DNSServer) { $DNSServer } else { $auditData.DNSServer }
    Write-Output "Target DNS Server: $dnsServer"

    $allRecords = $auditData.Records
    $filteredRecords = Get-FilteredRecords -Records $allRecords -AgeFilter $AgeFilter -ZoneFilter $ZoneFilter -RecordTypeFilter $RecordTypeFilter

    $script:CheckOnline = $CheckOnline

    if ($CheckOnline) {
        Write-Output ""
        Write-Output "Checking online status for A/AAAA records..."

        $recordsWithIP = $filteredRecords | Where-Object { $_.RecordType -eq "A" -or $_.RecordType -eq "AAAA" }
        
        foreach ($record in $recordsWithIP) {
            $online = Test-DeviceOnline -IPAddress $record.RecordData
            $record | Add-Member -NotePropertyName "OnlineStatus" -NotePropertyValue $online -Force
        }

        $offlineCount = ($recordsWithIP | Where-Object { $_.OnlineStatus -eq $false }).Count
        $onlineCount = ($recordsWithIP | Where-Object { $_.OnlineStatus -eq $true }).Count
        $otherCount = ($filteredRecords | Where-Object { $_.RecordType -ne "A" -and $_.RecordType -ne "AAAA" }).Count

        Write-Output "Online status check complete:"
        Write-Output "  Online: $onlineCount"
        Write-Output "  Offline: $offlineCount"
        Write-Output "  Other record types: $otherCount"
    }

    if ($filteredRecords.Count -eq 0) {
        Write-Output "No records match the filter criteria. Exiting."
        exit
    }

    $selectedRecords = @()

    if ($AutoApprove) {
        $selectedRecords = $filteredRecords
    } else {
        while ($true) {
            $choice = Show-RecordSelectionMenu -Records $filteredRecords

            switch ($choice) {
                "1" {
                    Show-RecordList -Records $filteredRecords
                }
                "2" {
                    Write-Output ""
                    Write-Output "Age Categories:"
                    Write-Output "  1. Over 365 Days"
                    Write-Output "  2. Over 180 Days"
                    Write-Output "  3. Over 90 Days"
                    Write-Output "  4. Static"
                    $ageChoice = Read-Host "Select age category (1-4)"

                    $ageCategoryMap = @{
                        "1" = "Over365Days"
                        "2" = "Over180Days"
                        "3" = "Over90Days"
                        "4" = "Static"
                    }

                    if ($ageCategoryMap.ContainsKey($ageChoice)) {
                        $selectedRecords = $filteredRecords | Where-Object { $_.AgeCategory -eq $ageCategoryMap[$ageChoice] }
                        Write-Output "Selected $($selectedRecords.Count) records"
                        break
                    }
                }
                "3" {
                    $zones = $filteredRecords | Select-Object -ExpandProperty ZoneName -Unique | Sort-Object
                    Write-Output ""
                    Write-Output "Available zones:"
                    for ($i = 0; $i -lt $zones.Count; $i++) {
                        Write-Output "  $($i + 1). $($zones[$i])"
                    }
                    $zoneChoice = Read-Host "Select zone number"
                    $zoneIndex = [int]$zoneChoice - 1

                    if ($zoneIndex -ge 0 -and $zoneIndex -lt $zones.Count) {
                        $selectedZone = $zones[$zoneIndex]
                        $selectedRecords = $filteredRecords | Where-Object { $_.ZoneName -eq $selectedZone }
                        Write-Output "Selected $($selectedRecords.Count) records from zone: $selectedZone"
                        break
                    }
                }
                "4" {
                    $types = $filteredRecords | Select-Object -ExpandProperty RecordType -Unique | Sort-Object
                    Write-Output ""
                    Write-Output "Available record types:"
                    for ($i = 0; $i -lt $types.Count; $i++) {
                        Write-Output "  $($i + 1). $($types[$i])"
                    }
                    $typeChoice = Read-Host "Select record type number"
                    $typeIndex = [int]$typeChoice - 1

                    if ($typeIndex -ge 0 -and $typeIndex -lt $types.Count) {
                        $selectedType = $types[$typeIndex]
                        $selectedRecords = $filteredRecords | Where-Object { $_.RecordType -eq $selectedType }
                        Write-Output "Selected $($selectedRecords.Count) records of type: $selectedType"
                        break
                    }
                }
                "5" {
                    Show-RecordList -Records $filteredRecords
                    $selectedRecords = Select-RecordsByIndex -Records $filteredRecords
                    break
                }
                "6" {
                    $selectedRecords = $filteredRecords
                    break
                }
                "7" {
                    Export-FilteredRecordsToCSV -Records $filteredRecords -OutputPath $JSONPath
                    continue
                }
                "8" {
                    Write-Output "Exiting without making changes"
                    exit
                }
                default {
                    Write-Output "Invalid choice. Please try again."
                    continue
                }
            }

            break
        }
    }

    if ($selectedRecords.Count -gt 0) {
        $deletionLog = Remove-DNSRecords -Records $selectedRecords -Server $dnsServer -WhatIfMode:$WhatIf -AutoApprove:$AutoApprove

        if ($deletionLog.Count -gt 0) {
            Export-DeletionLog -Log $deletionLog -Path $LogPath
        }
    } else {
        Write-Output "No records selected for deletion"
    }

    Write-Output ""
    Write-Output "DNS Cleanup complete!"

} catch {
    Write-Error "DNS Cleanup failed: $_"
    Write-Error $_.ScriptStackTrace
    exit 1
}
